### ISSUE TITLE
Tutorial page security certificate expired

### ISSUE THREAD

**Issue by Hairyloon** [acrobotic/Ai_Ardulib_SSD1306#15]
> Web sites prove their identity via certificates, which are valid for a set time period. The certificate for learn.acrobotic.com expired on 11/02/2019.
Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by datasith** [comment]
Thanks! After way too much procrastination I've finally started migrating things over from a self-hosted site to the shopify instance running acrobotic.com. I'm sloooowly migrating and the final endpoint will be https://acrobotic.com/blogs/learning/ (WiP)
